[package]
name = "f128"
version = "0.1.3"
authors = ["Joshua Karns <jkarns275@gmail.com>"]
build = "build.rs"
license = "MIT"
description = "Bindings to the gcc quadmath library"

[dependencies]
num = "0.1"

[build-dependencies]
gcc = "0.3"
