[package]
name = "f128"
version = "0.1.1"
authors = ["Joshua Karns <jkarns275@gmail.com>"]
build = "build.rs"
description = "Bindings to the gcc software implemented f128 types, and native long doubles."
license = "MIT"

[dependencies]

[build-dependencies]
gcc = "0.3"

[[bin]]
name = "bin"
path = "src/lib.rs"
